version: "3"
services:
  ecap-server-container:
    image: ecap-server
    ports:
      - 8080:80
    stdin_open: true
    tty: true
  ecap-client-container:
    image: ecap-client
    ports:
      - 8081:80
    environment:
      - SERVER_IP=ecap-server-container
      - SERVER_PORT=
    stdin_open: true
    tty: true
